import { ImageResponse } from "next/og";
import { personal } from "@/lib/data";

/**
 * The card that appears when the site is pasted into LinkedIn, Slack or a
 * message. Without one, a portfolio link previews as a blank rectangle — which
 * is most of what a recruiter sees before deciding whether to open it.
 *
 * Generated by next/og rather than exported from a design tool, so it follows
 * data.ts. No custom fonts: ImageResponse would need the font binary fetched at
 * render time, and the system stack is legible at this size anyway.
 */

export const alt = `${personal.name} — ${personal.role}`;
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OpengraphImage() {
  return new ImageResponse(
    <div
      style={{
        height: "100%",
        width: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        background: "#0A0A0A",
        padding: "72px 80px",
        fontFamily: "sans-serif",
      }}
    >
      {/* A single brand rule, the same accent the site runs on. */}
      <div
        style={{
          display: "flex",
          width: 120,
          height: 6,
          background: "#3B82F6",
        }}
      />

      <div style={{ display: "flex", flexDirection: "column" }}>
        <div
          style={{
            fontSize: 92,
            fontWeight: 800,
            color: "#FAFAFA",
            letterSpacing: "-0.03em",
            lineHeight: 1,
          }}
        >
          {personal.name}
        </div>
        <div
          style={{
            marginTop: 24,
            fontSize: 40,
            color: "#3B82F6",
            fontWeight: 600,
          }}
        >
          {personal.role}
        </div>
        <div
          style={{
            marginTop: 20,
            fontSize: 28,
            color: "#A1A1AA",
            maxWidth: 900,
          }}
        >
          Distributed systems, cloud infrastructure, and AI features in
          production.
        </div>
      </div>

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          fontSize: 24,
          color: "#71717A",
        }}
      >
        <span>{personal.seeking}</span>
        <span>{personal.location}</span>
      </div>
    </div>,
    size,
  );
}
